# @see https://docs.github.com/en/actions
# @see https://github.com/marketplace?verification=verified_creator&type=actions
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull repository."
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: "Install."
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes \
            bison \
            cmake \
            flex \
            gcc \
            g++ \
            git \
            make \
            libglfw3-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxinerama-dev \
            libxcursor-dev \
            libgl1-mesa-dev \
            xvfb
          chmod u+x --recursive src/main/bash
      - name: "Build."
        run: |
          src/main/bash/build.sh
      - name: "Test."
        run: |
          src/main/bash/test.sh
      - name: "Player test."
        run: |
          src/main/bash/run.sh src/test/c/accept/06-graphics
          xvfb-run --auto-servernum src/main/bash/play.sh .build/story.json

name: "CI"

# @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  pull_request:
    types:
      - closed
      - reopened
  push:
